version: "3"
services:
  # riz-bot:
  #   build: ../
  #   container_name: riz-bot
  #   volumes:
  #     - ~/configs/riz-bot:/usr/src/app/config
  #   networks:
  #     - personal
  #   environment:
  #     DISCORD_TOEKN: ""
  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - personal
    volumes:
      - ~/storage/redis:/data
    ports:
      - 6379:6379
    restart: always
  mongo:
    image: bitnami/mongodb:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_USERNAME: bot
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: riz-bot
networks:
  personal:
    external: false
